version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: quarkus
      MYSQL_PASSWORD: quarkus
      MYSQL_DATABASE: quarkusdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
